[package]
name = "rustcast"
version = "0.1.0"
authors = ["Dorian Burihabwa <dorian@burihabwa.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
